version: "3.8"

services:
    server:
        container_name: nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "80:80"
        networks:
            - app-network
        volumes:
            - ../:/var/www
            - ../docker/nginx/conf.d:/etc/nginx/conf.d/
        links:
            - app
            - db

    app:
        container_name: laravel
        build:
            dockerfile: Dockerfile.dev
        restart: unless-stopped
        volumes:
            - ../:/var/www
        networks:
            - app-network

    db:
        container_name: mysql
        image: arm64v8/mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
